[package]
name = "coop-projecty"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = ["default_fonts", "glow", "persistence"] }
native-dialog = "0.7.0"
webbrowser = "0.6"

